### ISSUE TITLE
Improve backup procedure -- rsync first, tar after

### ISSUE THREAD

**Issue by e-t-k** [UCSC-MedBook/MedBook#9]
Consider & implement per Rob's comment on #8 :

> To keep the load down on production and reduce network I/O I propose we rsync everything to backup before tar - that way only incremental blob store is backed up. Then on backup.medbook.io we could periodically tar up complete backup. Most of the time the rsync will only be coping changed files and the mongo dump (and 'might' send a diff of it, not sure)

**Comment by rcurrie** [comment]
I've coded up a new backup that rsync's everything to another server before tarring, but unfortunately the remote tar operation takes a ton of memory due to the size of the mongo db. Newer versions of mongodump support going directly to/from an archive which will be much more efficient so postponing this until we upgrade to a newer version of mongo.

**Comment by e-t-k** [comment]
@rcurrie Can you add your new backup to medbook_ ? Seems like we can revive this now that we're on mongo 3.2

**Comment by mokolodi1** [comment]
https://github.com/UCSC-MedBook/MedBook_/blob/master/docker-compose-mongo.yml#L9

**Comment by e-t-k** [comment]
Sorry @mokolodi1 , I meant "where is the new code that rob has written", not "where are we specifying mongo 3.2"

**Comment by rcurrie** [comment]
New backup code? It never was writting. There was the start of a script that cameron was going to finish but pipelines took that over. Lets chat about the approach.
